#ifndef ENUMERATIONS_H_INCLUDED
#define ENUMERATIONS_H_INCLUDED

enum selected {
    ID_FLAG_IS_PICKABLE = 10000,
    ID_FLAG_IS_DRAGABLE,
    ID_FLAG_FONDO,
    ID_FLAG
};

enum tournamentsID {
    TOURNAMENT_TETRA_TOURNAMENT = 20000,
    TOURNAMENT_HEXA_TOURNAMENT,
    TOURNAMENT_OCTA_TOURNAMENT,
    TOURNAMENT_D0DECA_TOURNAMENT,
    TOURNAMENT_ICOSA_TOURNAMENT
};

enum playersID {
    PLAYER_1 = 30000,
    PLAYER_2,
    PLAYER_3,
    PLAYER_4,
    PLAYER_5
};

enum colorsID {
    COLOR_1 = 40000,
    COLOR_2,
    COLOR_3,
    COLOR_4,
    COLOR_5
};

enum languages {
    PLAYTON_SPANISH = 50000,
    PLAYTON_ENGLISH,
    PLAYTON_FRENCH
};

enum options {
    GUI_ID_QUIT_BUTTON = 60000,
    GUI_ID_OPTIONS_BUTTON,
    GUI_ID_FILE_OPEN_BUTTON,
    GUI_ID_CLOSE_WINDOW_BUTTON,
    GUI_ID_CLOSE_BUTTON
};

enum numbers {
    GUI_ID_1 = 70000,
    GUI_ID_2,
    GUI_ID_3,
    GUI_ID_4,
    GUI_ID_5,
    GUI_ID_6,
};

enum operands {
    GUI_ID_PLUS = 80000,
    GUI_ID_MINUS,
    GUI_ID_MULT,
    GUI_ID_DIV,
    GUI_ID_EQUAL,
};

enum buttons {
    GUI_ID_INSTRUCTIONS = 90000,
    GUI_ID_SETUP,
    GUI_ID_PLAY,
    GUI_ID_ILUSTRATION,
    GUI_ID_CREDITS,
    GUI_ID_SALIR,
    GUI_ID_CHECKED,
    GUI_ID_CHECKED_PLAYER,
    GUI_ID_CHECKED_COLOR,
    GUI_ID_CHECKED_WINNER,
    GUI_ID_CLOSE_WINDOW,
    GUI_ID_SPANISH,
    GUI_ID_FRENCH,
    GUI_ID_ENGLISH,
    GUI_ID_TOURNAMENT,
    GUI_ID_SIMPLE,
    GUI_ID_PLAY_NOW,
    GUI_ID_SELECT_COLOR,
    GUI_ID_WINDOW_COLOR,
    GUI_ID_PLAYTON,
    GUI_ID_MENU,
    GUI_ID_TOTALEDRUM,
    GUI_ID_PLAY_AGAIN,
    GUI_ID_CONTROL_MUSIC,
    GUI_ID_CONTROL_EFFECTS,
    GUI_ID_CONTROL_TEXTURES
};

enum platonics {
    HEXAEDRO = 110000,
    TETRAEDRO,
    ICOSAEDRO,
    OCTAEDRO,
    DODECAEDRO
};

enum colors {
    RED = 120000,
    GREEN,
    YELLOW,
    PURPLE,
    BLUE,
};

enum sounds {
    PLAYTON_MAIN = 130000,
    ALL_SOUNDS,
    EFFECT_SOUNDS
};

#endif // ENUMERATIONS_H_INCLUDED